/**
 * Complaints DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaints
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Complaints Domain Module - Composition root
 *
 * DDD: Composition root for complaints domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ComplaintRepositoryAdapter,
} from "@klarwatt/adapters/complaints";
import { getIdGeneratorService } from "@klarwatt/adapters";
import type { AdapterDynamoDBClient } from "@klarwatt/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteListComplaints,
  ExecuteRecogniseComplaint,
} from "@klarwatt/services/complaints/usecases";
// Ports (interfaces)
import type {
  ComplaintRepository,
} from "@klarwatt/services/complaints/ports";

export interface ComplaintsDomainModule {
  repos: {
    complaints: ComplaintRepository;
  };
  useCases: {
    complaints: {
      get: ExecuteRecogniseComplaint;
      list: ExecuteListComplaints;
    };
  };
}

export function buildComplaintsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ComplaintsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      complaints?: ComplaintRepository;
    } = {};

    obj.complaints = new ComplaintRepositoryAdapter(dynamoClient);
    return {
      complaints: obj.complaints!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    complaints: {
      get: new ExecuteRecogniseComplaint(executionContext, idGenerator, repos.complaints),
      list: new ExecuteListComplaints(executionContext, idGenerator, repos.complaints),
    },
  };
  return { repos, useCases: useCases as ComplaintsDomainModule["useCases"] };
}
