/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contact Sessions */
        get: operations["listContactSessions"];
        put?: never;
        /** Open Contact Session */
        post: operations["openContactSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contacts/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        /** Get Contact Session */
        get: operations["getContactSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contacts/{sessionId}/intents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Classify Contact Intent */
        post: operations["classifyContactIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contacts/{sessionId}/handover": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Escalate To Advisor */
        post: operations["escalateToAdvisor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contacts/{sessionId}/advisor-correction": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Advisor Correction */
        post: operations["recordAdvisorCorrection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{accountId}/context": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        /** Get Account Context */
        get: operations["getAccountContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Channel: "voice" | "chat" | "mobile_app" | "web_form" | "email" | "sms";
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description The licensed role the automated agent speaks in for this interaction
         * @enum {string}
         */
        RegulatedRole: "supplier" | "network_operator" | "affiliated_service_provider";
        /** @enum {string} */
        MeteringGranularity: "monthly_total" | "daily" | "hourly" | "half_hourly";
        ContactSession: {
            id: string;
            /** @enum {string} */
            channel: "voice" | "chat" | "mobile_app" | "web_form" | "email" | "sms";
            accountId?: string;
            meterPointId?: string;
            /**
             * @description The licensed role the automated agent speaks in for this interaction
             * @enum {string}
             */
            regulatedRole: "supplier" | "network_operator" | "affiliated_service_provider";
            purposeId: string;
            /** @enum {string} */
            granularityCeiling?: "monthly_total" | "daily" | "hourly" | "half_hourly";
            /** @enum {string} */
            outcome: "in_progress" | "resolved" | "escalated" | "abandoned" | "blocked_by_policy";
            firstContactResolution?: boolean;
            /** @description Named data elements read during the interaction */
            dataUsed?: string[];
            /** @description Capability release version that served this interaction */
            releaseId?: string;
            cohortId?: string;
            explanationCorrectedByAdvisor?: boolean;
            /** Format: date-time */
            openedAt?: string;
            secondsToFirstSubstantiveAnswer?: number;
            /** @description Pinned automation capability version that served this session (BR-12). */
            releaseVersionId?: string;
            /** @description Advisor handover package completeness (conversation, data used, reason). */
            packageCompleteness?: number;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        ContactSessionListResponse: {
            data: {
                items: {
                    id: string;
                    /** @enum {string} */
                    channel: "voice" | "chat" | "mobile_app" | "web_form" | "email" | "sms";
                    accountId?: string;
                    meterPointId?: string;
                    /**
                     * @description The licensed role the automated agent speaks in for this interaction
                     * @enum {string}
                     */
                    regulatedRole: "supplier" | "network_operator" | "affiliated_service_provider";
                    purposeId: string;
                    /** @enum {string} */
                    granularityCeiling?: "monthly_total" | "daily" | "hourly" | "half_hourly";
                    /** @enum {string} */
                    outcome: "in_progress" | "resolved" | "escalated" | "abandoned" | "blocked_by_policy";
                    firstContactResolution?: boolean;
                    /** @description Named data elements read during the interaction */
                    dataUsed?: string[];
                    /** @description Capability release version that served this interaction */
                    releaseId?: string;
                    cohortId?: string;
                    explanationCorrectedByAdvisor?: boolean;
                    /** Format: date-time */
                    openedAt?: string;
                    secondsToFirstSubstantiveAnswer?: number;
                    /** @description Pinned automation capability version that served this session (BR-12). */
                    releaseVersionId?: string;
                    /** @description Advisor handover package completeness (conversation, data used, reason). */
                    packageCompleteness?: number;
                }[];
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        ContactSessionCreate: {
            /** @enum {string} */
            channel: "voice" | "chat" | "mobile_app" | "web_form" | "email" | "sms";
            accountReference: string;
            meterPointId?: string;
            /**
             * @description The licensed role the automated agent speaks in for this interaction
             * @enum {string}
             */
            declaredRole?: "supplier" | "network_operator" | "affiliated_service_provider";
            purposeId?: string;
            cohortId?: string;
        };
        ContactSessionResponse: {
            data: {
                id: string;
                /** @enum {string} */
                channel: "voice" | "chat" | "mobile_app" | "web_form" | "email" | "sms";
                accountId?: string;
                meterPointId?: string;
                /**
                 * @description The licensed role the automated agent speaks in for this interaction
                 * @enum {string}
                 */
                regulatedRole: "supplier" | "network_operator" | "affiliated_service_provider";
                purposeId: string;
                /** @enum {string} */
                granularityCeiling?: "monthly_total" | "daily" | "hourly" | "half_hourly";
                /** @enum {string} */
                outcome: "in_progress" | "resolved" | "escalated" | "abandoned" | "blocked_by_policy";
                firstContactResolution?: boolean;
                /** @description Named data elements read during the interaction */
                dataUsed?: string[];
                /** @description Capability release version that served this interaction */
                releaseId?: string;
                cohortId?: string;
                explanationCorrectedByAdvisor?: boolean;
                /** Format: date-time */
                openedAt?: string;
                secondsToFirstSubstantiveAnswer?: number;
                /** @description Pinned automation capability version that served this session (BR-12). */
                releaseVersionId?: string;
                /** @description Advisor handover package completeness (conversation, data used, reason). */
                packageCompleteness?: number;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        Intent: {
            /** @enum {string} */
            name: "bill_higher_than_expected" | "consumption_query" | "meter_read_dispute" | "tariff_change_query" | "payment_difficulty" | "disconnection_query" | "move_in_move_out" | "outage_query" | "meter_fault" | "complaint";
            /** Format: float */
            confidence: number;
            triggersVulnerabilityGate?: boolean;
            /** @enum {string} */
            requiredGranularity?: "monthly_total" | "daily" | "hourly" | "half_hourly";
        };
        IntentResponse: {
            data: {
                /** @enum {string} */
                name: "bill_higher_than_expected" | "consumption_query" | "meter_read_dispute" | "tariff_change_query" | "payment_difficulty" | "disconnection_query" | "move_in_move_out" | "outage_query" | "meter_fault" | "complaint";
                /** Format: float */
                confidence: number;
                triggersVulnerabilityGate?: boolean;
                /** @enum {string} */
                requiredGranularity?: "monthly_total" | "daily" | "hourly" | "half_hourly";
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        EscalationEvent: {
            id: string;
            sessionId: string;
            /** @enum {string} */
            reason: "vulnerability_gate" | "outside_policy" | "low_confidence" | "customer_request" | "unbundling_block" | "data_unavailable";
            targetQueue?: string;
            packageComplete?: boolean;
            conversationTranscriptRef?: string;
            dataUsed?: string[];
            /** Format: date-time */
            escalatedAt?: string;
        };
        EscalationEventResponse: {
            data: {
                id: string;
                sessionId: string;
                /** @enum {string} */
                reason: "vulnerability_gate" | "outside_policy" | "low_confidence" | "customer_request" | "unbundling_block" | "data_unavailable";
                targetQueue?: string;
                packageComplete?: boolean;
                conversationTranscriptRef?: string;
                dataUsed?: string[];
                /** Format: date-time */
                escalatedAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        Money: {
            /** Format: double */
            amount: number;
            /** @example EUR */
            currency: string;
        };
        CustomerAccount: {
            id: string;
            meterPointIds: string[];
            /** @enum {string} */
            paymentMethod?: "direct_debit" | "on_receipt" | "prepayment";
            arrearsBalance?: {
                /** Format: double */
                amount: number;
                /** @example EUR */
                currency: string;
            };
            priorityServicesRegistered?: boolean;
        };
        MeterPoint: {
            id: string;
            /** @enum {string} */
            commodity: "electricity" | "gas" | "heat";
            /** @enum {string} */
            meterType: "smart_interval" | "smart_daily" | "traditional";
            networkOperatorId?: string;
            /** @example PT24H */
            readSubmissionLag?: string;
        };
        TariffPlan: {
            id: string;
            name: string;
            /** @enum {string} */
            structure: "fixed" | "variable" | "time_of_use" | "dynamic";
            standingChargePerDay?: {
                /** Format: double */
                amount: number;
                /** @example EUR */
                currency: string;
            };
            unitRates?: {
                band?: string;
                pricePerKwh?: {
                    /** Format: double */
                    amount: number;
                    /** @example EUR */
                    currency: string;
                };
            }[];
            networkChargePassThrough?: boolean;
            /** Format: date */
            effectiveFrom?: string;
        };
        MeterReading: {
            meterPointId: string;
            /** Format: date-time */
            readAt: string;
            /** Format: double */
            valueKwh: number;
            /** @enum {string} */
            readType: "actual" | "estimated" | "customer_submitted" | "deemed";
            /** @enum {string} */
            granularity?: "monthly_total" | "daily" | "hourly" | "half_hourly";
        };
        AccountContext: {
            account: {
                id: string;
                meterPointIds: string[];
                /** @enum {string} */
                paymentMethod?: "direct_debit" | "on_receipt" | "prepayment";
                arrearsBalance?: {
                    /** Format: double */
                    amount: number;
                    /** @example EUR */
                    currency: string;
                };
                priorityServicesRegistered?: boolean;
            };
            meterPoints: {
                id: string;
                /** @enum {string} */
                commodity: "electricity" | "gas" | "heat";
                /** @enum {string} */
                meterType: "smart_interval" | "smart_daily" | "traditional";
                networkOperatorId?: string;
                /** @example PT24H */
                readSubmissionLag?: string;
            }[];
            currentTariff?: {
                id: string;
                name: string;
                /** @enum {string} */
                structure: "fixed" | "variable" | "time_of_use" | "dynamic";
                standingChargePerDay?: {
                    /** Format: double */
                    amount: number;
                    /** @example EUR */
                    currency: string;
                };
                unitRates?: {
                    band?: string;
                    pricePerKwh?: {
                        /** Format: double */
                        amount: number;
                        /** @example EUR */
                        currency: string;
                    };
                }[];
                networkChargePassThrough?: boolean;
                /** Format: date */
                effectiveFrom?: string;
            };
            previousTariff?: {
                id: string;
                name: string;
                /** @enum {string} */
                structure: "fixed" | "variable" | "time_of_use" | "dynamic";
                standingChargePerDay?: {
                    /** Format: double */
                    amount: number;
                    /** @example EUR */
                    currency: string;
                };
                unitRates?: {
                    band?: string;
                    pricePerKwh?: {
                        /** Format: double */
                        amount: number;
                        /** @example EUR */
                        currency: string;
                    };
                }[];
                networkChargePassThrough?: boolean;
                /** Format: date */
                effectiveFrom?: string;
            };
            recentReadings?: {
                meterPointId: string;
                /** Format: date-time */
                readAt: string;
                /** Format: double */
                valueKwh: number;
                /** @enum {string} */
                readType: "actual" | "estimated" | "customer_submitted" | "deemed";
                /** @enum {string} */
                granularity?: "monthly_total" | "daily" | "hourly" | "half_hourly";
            }[];
            /** @enum {string} */
            granularityCeiling: "monthly_total" | "daily" | "hourly" | "half_hourly";
            purposeId?: string;
        };
        AccountContextResponse: {
            data: {
                account: {
                    id: string;
                    meterPointIds: string[];
                    /** @enum {string} */
                    paymentMethod?: "direct_debit" | "on_receipt" | "prepayment";
                    arrearsBalance?: {
                        /** Format: double */
                        amount: number;
                        /** @example EUR */
                        currency: string;
                    };
                    priorityServicesRegistered?: boolean;
                };
                meterPoints: {
                    id: string;
                    /** @enum {string} */
                    commodity: "electricity" | "gas" | "heat";
                    /** @enum {string} */
                    meterType: "smart_interval" | "smart_daily" | "traditional";
                    networkOperatorId?: string;
                    /** @example PT24H */
                    readSubmissionLag?: string;
                }[];
                currentTariff?: {
                    id: string;
                    name: string;
                    /** @enum {string} */
                    structure: "fixed" | "variable" | "time_of_use" | "dynamic";
                    standingChargePerDay?: {
                        /** Format: double */
                        amount: number;
                        /** @example EUR */
                        currency: string;
                    };
                    unitRates?: {
                        band?: string;
                        pricePerKwh?: {
                            /** Format: double */
                            amount: number;
                            /** @example EUR */
                            currency: string;
                        };
                    }[];
                    networkChargePassThrough?: boolean;
                    /** Format: date */
                    effectiveFrom?: string;
                };
                previousTariff?: {
                    id: string;
                    name: string;
                    /** @enum {string} */
                    structure: "fixed" | "variable" | "time_of_use" | "dynamic";
                    standingChargePerDay?: {
                        /** Format: double */
                        amount: number;
                        /** @example EUR */
                        currency: string;
                    };
                    unitRates?: {
                        band?: string;
                        pricePerKwh?: {
                            /** Format: double */
                            amount: number;
                            /** @example EUR */
                            currency: string;
                        };
                    }[];
                    networkChargePassThrough?: boolean;
                    /** Format: date */
                    effectiveFrom?: string;
                };
                recentReadings?: {
                    meterPointId: string;
                    /** Format: date-time */
                    readAt: string;
                    /** Format: double */
                    valueKwh: number;
                    /** @enum {string} */
                    readType: "actual" | "estimated" | "customer_submitted" | "deemed";
                    /** @enum {string} */
                    granularity?: "monthly_total" | "daily" | "hourly" | "half_hourly";
                }[];
                /** @enum {string} */
                granularityCeiling: "monthly_total" | "daily" | "hourly" | "half_hourly";
                purposeId?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Semantically invalid request (e.g. PACK_EMPTY) */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /** @description Opaque keyset cursor for list pages. */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
        SessionId: string;
        AccountId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listContactSessions: {
        parameters: {
            query?: {
                /** @description Opaque keyset cursor for list pages. */
                cursor?: string;
                /** @description Page size. */
                limit?: number;
                outcome?: "resolved" | "escalated" | "abandoned" | "blocked_by_policy";
                channel?: "voice" | "chat" | "mobile_app" | "web_form" | "email" | "sms";
                /** @description Advisor desk: only sessions with an active vulnerability flag (WEBAPP live queue). */
                vulnerabilityOnly?: boolean;
                /** @description Advisor desk: only sessions with a running complaint regulatory clock. */
                complaintClockRunning?: boolean;
                /** @description Live / escalated queue filter. */
                escalatedOnly?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contact sessions page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                /** @enum {string} */
                                channel: "voice" | "chat" | "mobile_app" | "web_form" | "email" | "sms";
                                accountId?: string;
                                meterPointId?: string;
                                /**
                                 * @description The licensed role the automated agent speaks in for this interaction
                                 * @enum {string}
                                 */
                                regulatedRole: "supplier" | "network_operator" | "affiliated_service_provider";
                                purposeId: string;
                                /** @enum {string} */
                                granularityCeiling?: "monthly_total" | "daily" | "hourly" | "half_hourly";
                                /** @enum {string} */
                                outcome: "in_progress" | "resolved" | "escalated" | "abandoned" | "blocked_by_policy";
                                firstContactResolution?: boolean;
                                /** @description Named data elements read during the interaction */
                                dataUsed?: string[];
                                /** @description Capability release version that served this interaction */
                                releaseId?: string;
                                cohortId?: string;
                                explanationCorrectedByAdvisor?: boolean;
                                /** Format: date-time */
                                openedAt?: string;
                                secondsToFirstSubstantiveAnswer?: number;
                                /** @description Pinned automation capability version that served this session (BR-12). */
                                releaseVersionId?: string;
                                /** @description Advisor handover package completeness (conversation, data used, reason). */
                                packageCompleteness?: number;
                            }[];
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    openContactSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    channel: "voice" | "chat" | "mobile_app" | "web_form" | "email" | "sms";
                    accountReference: string;
                    meterPointId?: string;
                    /**
                     * @description The licensed role the automated agent speaks in for this interaction
                     * @enum {string}
                     */
                    declaredRole?: "supplier" | "network_operator" | "affiliated_service_provider";
                    purposeId?: string;
                    cohortId?: string;
                };
            };
        };
        responses: {
            /** @description Session opened with account, meter point, and regulated role resolved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            /** @enum {string} */
                            channel: "voice" | "chat" | "mobile_app" | "web_form" | "email" | "sms";
                            accountId?: string;
                            meterPointId?: string;
                            /**
                             * @description The licensed role the automated agent speaks in for this interaction
                             * @enum {string}
                             */
                            regulatedRole: "supplier" | "network_operator" | "affiliated_service_provider";
                            purposeId: string;
                            /** @enum {string} */
                            granularityCeiling?: "monthly_total" | "daily" | "hourly" | "half_hourly";
                            /** @enum {string} */
                            outcome: "in_progress" | "resolved" | "escalated" | "abandoned" | "blocked_by_policy";
                            firstContactResolution?: boolean;
                            /** @description Named data elements read during the interaction */
                            dataUsed?: string[];
                            /** @description Capability release version that served this interaction */
                            releaseId?: string;
                            cohortId?: string;
                            explanationCorrectedByAdvisor?: boolean;
                            /** Format: date-time */
                            openedAt?: string;
                            secondsToFirstSubstantiveAnswer?: number;
                            /** @description Pinned automation capability version that served this session (BR-12). */
                            releaseVersionId?: string;
                            /** @description Advisor handover package completeness (conversation, data used, reason). */
                            packageCompleteness?: number;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Semantically invalid request (e.g. PACK_EMPTY) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getContactSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session with role, purpose, data used, and pinned release version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            /** @enum {string} */
                            channel: "voice" | "chat" | "mobile_app" | "web_form" | "email" | "sms";
                            accountId?: string;
                            meterPointId?: string;
                            /**
                             * @description The licensed role the automated agent speaks in for this interaction
                             * @enum {string}
                             */
                            regulatedRole: "supplier" | "network_operator" | "affiliated_service_provider";
                            purposeId: string;
                            /** @enum {string} */
                            granularityCeiling?: "monthly_total" | "daily" | "hourly" | "half_hourly";
                            /** @enum {string} */
                            outcome: "in_progress" | "resolved" | "escalated" | "abandoned" | "blocked_by_policy";
                            firstContactResolution?: boolean;
                            /** @description Named data elements read during the interaction */
                            dataUsed?: string[];
                            /** @description Capability release version that served this interaction */
                            releaseId?: string;
                            cohortId?: string;
                            explanationCorrectedByAdvisor?: boolean;
                            /** Format: date-time */
                            openedAt?: string;
                            secondsToFirstSubstantiveAnswer?: number;
                            /** @description Pinned automation capability version that served this session (BR-12). */
                            releaseVersionId?: string;
                            /** @description Advisor handover package completeness (conversation, data used, reason). */
                            packageCompleteness?: number;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    classifyContactIntent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    utterance: string;
                };
            };
        };
        responses: {
            /** @description Intent classified within the purpose and granularity envelope */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @enum {string} */
                            name: "bill_higher_than_expected" | "consumption_query" | "meter_read_dispute" | "tariff_change_query" | "payment_difficulty" | "disconnection_query" | "move_in_move_out" | "outage_query" | "meter_fault" | "complaint";
                            /** Format: float */
                            confidence: number;
                            triggersVulnerabilityGate?: boolean;
                            /** @enum {string} */
                            requiredGranularity?: "monthly_total" | "daily" | "hourly" | "half_hourly";
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    escalateToAdvisor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    reason: "vulnerability_gate" | "outside_policy" | "low_confidence" | "customer_request" | "unbundling_block" | "data_unavailable";
                    targetQueue?: string;
                };
            };
        };
        responses: {
            /** @description Escalation dispatched with conversation, data used, and reason */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            sessionId: string;
                            /** @enum {string} */
                            reason: "vulnerability_gate" | "outside_policy" | "low_confidence" | "customer_request" | "unbundling_block" | "data_unavailable";
                            targetQueue?: string;
                            packageComplete?: boolean;
                            conversationTranscriptRef?: string;
                            dataUsed?: string[];
                            /** Format: date-time */
                            escalatedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    recordAdvisorCorrection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    wasExplanationCorrect: boolean;
                    advisorReference: string;
                    correctExplanation?: string;
                    suspectedDataDefect?: boolean;
                };
            };
        };
        responses: {
            /** @description Correction recorded; incorrect explanations leave resolution metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            /** @enum {string} */
                            channel: "voice" | "chat" | "mobile_app" | "web_form" | "email" | "sms";
                            accountId?: string;
                            meterPointId?: string;
                            /**
                             * @description The licensed role the automated agent speaks in for this interaction
                             * @enum {string}
                             */
                            regulatedRole: "supplier" | "network_operator" | "affiliated_service_provider";
                            purposeId: string;
                            /** @enum {string} */
                            granularityCeiling?: "monthly_total" | "daily" | "hourly" | "half_hourly";
                            /** @enum {string} */
                            outcome: "in_progress" | "resolved" | "escalated" | "abandoned" | "blocked_by_policy";
                            firstContactResolution?: boolean;
                            /** @description Named data elements read during the interaction */
                            dataUsed?: string[];
                            /** @description Capability release version that served this interaction */
                            releaseId?: string;
                            cohortId?: string;
                            explanationCorrectedByAdvisor?: boolean;
                            /** Format: date-time */
                            openedAt?: string;
                            secondsToFirstSubstantiveAnswer?: number;
                            /** @description Pinned automation capability version that served this session (BR-12). */
                            releaseVersionId?: string;
                            /** @description Advisor handover package completeness (conversation, data used, reason). */
                            packageCompleteness?: number;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getAccountContext: {
        parameters: {
            query: {
                /** @description Lawful purpose under which the context is read */
                purposeId: string;
            };
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account, meter points, tariff, and reads within the purpose ceiling */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            account: {
                                id: string;
                                meterPointIds: string[];
                                /** @enum {string} */
                                paymentMethod?: "direct_debit" | "on_receipt" | "prepayment";
                                arrearsBalance?: {
                                    /** Format: double */
                                    amount: number;
                                    /** @example EUR */
                                    currency: string;
                                };
                                priorityServicesRegistered?: boolean;
                            };
                            meterPoints: {
                                id: string;
                                /** @enum {string} */
                                commodity: "electricity" | "gas" | "heat";
                                /** @enum {string} */
                                meterType: "smart_interval" | "smart_daily" | "traditional";
                                networkOperatorId?: string;
                                /** @example PT24H */
                                readSubmissionLag?: string;
                            }[];
                            currentTariff?: {
                                id: string;
                                name: string;
                                /** @enum {string} */
                                structure: "fixed" | "variable" | "time_of_use" | "dynamic";
                                standingChargePerDay?: {
                                    /** Format: double */
                                    amount: number;
                                    /** @example EUR */
                                    currency: string;
                                };
                                unitRates?: {
                                    band?: string;
                                    pricePerKwh?: {
                                        /** Format: double */
                                        amount: number;
                                        /** @example EUR */
                                        currency: string;
                                    };
                                }[];
                                networkChargePassThrough?: boolean;
                                /** Format: date */
                                effectiveFrom?: string;
                            };
                            previousTariff?: {
                                id: string;
                                name: string;
                                /** @enum {string} */
                                structure: "fixed" | "variable" | "time_of_use" | "dynamic";
                                standingChargePerDay?: {
                                    /** Format: double */
                                    amount: number;
                                    /** @example EUR */
                                    currency: string;
                                };
                                unitRates?: {
                                    band?: string;
                                    pricePerKwh?: {
                                        /** Format: double */
                                        amount: number;
                                        /** @example EUR */
                                        currency: string;
                                    };
                                }[];
                                networkChargePassThrough?: boolean;
                                /** Format: date */
                                effectiveFrom?: string;
                            };
                            recentReadings?: {
                                meterPointId: string;
                                /** Format: date-time */
                                readAt: string;
                                /** Format: double */
                                valueKwh: number;
                                /** @enum {string} */
                                readType: "actual" | "estimated" | "customer_submitted" | "deemed";
                                /** @enum {string} */
                                granularity?: "monthly_total" | "daily" | "hourly" | "half_hourly";
                            }[];
                            /** @enum {string} */
                            granularityCeiling: "monthly_total" | "daily" | "hourly" | "half_hourly";
                            purposeId?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Purpose does not permit reading this context */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
