/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@klarwatt/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildAdviceDomainModule,
  buildCohortsDomainModule,
  buildComplaintsDomainModule,
  buildComplianceDomainModule,
  buildConsentDomainModule,
  buildConsumptionDomainModule,
  buildContactsDomainModule,
  buildIdentityDomainModule,
  buildResolutionsDomainModule,
  buildVulnerabilityDomainModule,
} from "../domains/index.js";
import type {
  AdviceDomainModule,
  CohortsDomainModule,
  ComplaintsDomainModule,
  ComplianceDomainModule,
  ConsentDomainModule,
  ConsumptionDomainModule,
  ContactsDomainModule,
  IdentityDomainModule,
  ResolutionsDomainModule,
  VulnerabilityDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private adviceModule: AdviceDomainModule | null = null;
  private cohortsModule: CohortsDomainModule | null = null;
  private complaintsModule: ComplaintsDomainModule | null = null;
  private complianceModule: ComplianceDomainModule | null = null;
  private consentModule: ConsentDomainModule | null = null;
  private consumptionModule: ConsumptionDomainModule | null = null;
  private contactsModule: ContactsDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private resolutionsModule: ResolutionsDomainModule | null = null;
  private vulnerabilityModule: VulnerabilityDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get advice domain module
   */
  getAdviceDependencies(): AdviceDomainModule {
    if (!this.adviceModule) {
      this.adviceModule = buildAdviceDomainModule(this.dynamoClient);
    }
    return this.adviceModule;
  }

  /**
   * Get cohorts domain module
   */
  getCohortsDependencies(): CohortsDomainModule {
    if (!this.cohortsModule) {
      this.cohortsModule = buildCohortsDomainModule(this.dynamoClient);
    }
    return this.cohortsModule;
  }

  /**
   * Get complaints domain module
   */
  getComplaintsDependencies(): ComplaintsDomainModule {
    if (!this.complaintsModule) {
      this.complaintsModule = buildComplaintsDomainModule(this.dynamoClient);
    }
    return this.complaintsModule;
  }

  /**
   * Get compliance domain module
   */
  getComplianceDependencies(): ComplianceDomainModule {
    if (!this.complianceModule) {
      this.complianceModule = buildComplianceDomainModule(this.dynamoClient);
    }
    return this.complianceModule;
  }

  /**
   * Get consent domain module
   */
  getConsentDependencies(): ConsentDomainModule {
    if (!this.consentModule) {
      this.consentModule = buildConsentDomainModule(this.dynamoClient);
    }
    return this.consentModule;
  }

  /**
   * Get consumption domain module
   */
  getConsumptionDependencies(): ConsumptionDomainModule {
    if (!this.consumptionModule) {
      this.consumptionModule = buildConsumptionDomainModule(this.dynamoClient);
    }
    return this.consumptionModule;
  }

  /**
   * Get contacts domain module
   */
  getContactsDependencies(): ContactsDomainModule {
    if (!this.contactsModule) {
      this.contactsModule = buildContactsDomainModule(this.dynamoClient);
    }
    return this.contactsModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get resolutions domain module
   */
  getResolutionsDependencies(): ResolutionsDomainModule {
    if (!this.resolutionsModule) {
      this.resolutionsModule = buildResolutionsDomainModule(this.dynamoClient);
    }
    return this.resolutionsModule;
  }

  /**
   * Get vulnerability domain module
   */
  getVulnerabilityDependencies(): VulnerabilityDomainModule {
    if (!this.vulnerabilityModule) {
      this.vulnerabilityModule = buildVulnerabilityDomainModule(this.dynamoClient);
    }
    return this.vulnerabilityModule;
  }

  clearAdviceDependencies(): void { this.adviceModule = null; }
  clearCohortsDependencies(): void { this.cohortsModule = null; }
  clearComplaintsDependencies(): void { this.complaintsModule = null; }
  clearComplianceDependencies(): void { this.complianceModule = null; }
  clearConsentDependencies(): void { this.consentModule = null; }
  clearConsumptionDependencies(): void { this.consumptionModule = null; }
  clearContactsDependencies(): void { this.contactsModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearResolutionsDependencies(): void { this.resolutionsModule = null; }
  clearVulnerabilityDependencies(): void { this.vulnerabilityModule = null; }

  getAdviceDependenciesForRequest(): AdviceDomainModule {
    return this.getAdviceDependencies();
  }

  getCohortsDependenciesForRequest(): CohortsDomainModule {
    return this.getCohortsDependencies();
  }

  getComplaintsDependenciesForRequest(): ComplaintsDomainModule {
    return this.getComplaintsDependencies();
  }

  getComplianceDependenciesForRequest(): ComplianceDomainModule {
    return this.getComplianceDependencies();
  }

  getConsentDependenciesForRequest(): ConsentDomainModule {
    return this.getConsentDependencies();
  }

  getConsumptionDependenciesForRequest(): ConsumptionDomainModule {
    return this.getConsumptionDependencies();
  }

  getContactsDependenciesForRequest(): ContactsDomainModule {
    return this.getContactsDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getResolutionsDependenciesForRequest(): ResolutionsDomainModule {
    return this.getResolutionsDependencies();
  }

  getVulnerabilityDependenciesForRequest(): VulnerabilityDomainModule {
    return this.getVulnerabilityDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.adviceModule = null;
    this.cohortsModule = null;
    this.complaintsModule = null;
    this.complianceModule = null;
    this.consentModule = null;
    this.consumptionModule = null;
    this.contactsModule = null;
    this.identityModule = null;
    this.resolutionsModule = null;
    this.vulnerabilityModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
