/**
 * Context DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Context DTOs
 *
 * DDD: Application DTOs for Context use cases.
 */

import type { GetAccountContextParams } from "@klarwatt/core/contacts/types";

export type GetAccountContextInput = GetAccountContextParams;

export type GetAccountContextOutput = {};
