/**
 * Handover DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Handover DTOs
 *
 * DDD: Application DTOs for Handover use cases.
 */

import type { EscalateToAdvisorParams, EscalateToAdvisorRequestInput } from "@klarwatt/core/contacts/types";

export type EscalateToAdvisorInput = EscalateToAdvisorParams & EscalateToAdvisorRequestInput;

export type EscalateToAdvisorOutput = {};
