/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consumption
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Consumption Domain Use Cases
 * 
 * List of all use case names for the consumption domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const CONSUMPTION_USE_CASES = [
  "executeExplainConsumptionChange",
  "executeListEstimatedReadCorrections",
  "executeRaiseDataDefectReport"
] as const;
