/**
 * ContextRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContextRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ContextRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ContextRepository,
} from "@klarwatt/services/contacts";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ContextRepositoryDdb } from "./context-repository.ddb.js";

/**
 * ContextRepositoryAdapter
 *
 * Implements ContextRepository port for infrastructure layer.
 */
export class ContextRepositoryAdapter implements ContextRepository {
  private readonly ddb: ContextRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ContextRepositoryDdb(this.dynamoClient);
  }

  async getAccountContext(input: Parameters<ContextRepository['getAccountContext']>[0]): Promise<Awaited<ReturnType<ContextRepository['getAccountContext']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAccountContext(input);
  }
}
