/**
 * ContactRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContactRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ContactRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ContactRepository,
} from "@klarwatt/services/contacts";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ContactRepositoryDdb } from "./contact-repository.ddb.js";

/**
 * ContactRepositoryAdapter
 *
 * Implements ContactRepository port for infrastructure layer.
 */
export class ContactRepositoryAdapter implements ContactRepository {
  private readonly ddb: ContactRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ContactRepositoryDdb(this.dynamoClient);
  }

  async openContactSession(input: Parameters<ContactRepository['openContactSession']>[0]): Promise<Awaited<ReturnType<ContactRepository['openContactSession']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.openContactSession(input);
  }

  async listContactSessions(input: Parameters<ContactRepository['listContactSessions']>[0]): Promise<Awaited<ReturnType<ContactRepository['listContactSessions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listContactSessions(input);
  }

  async getContactSession(input: Parameters<ContactRepository['getContactSession']>[0]): Promise<Awaited<ReturnType<ContactRepository['getContactSession']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getContactSession(input);
  }
}
