/**
 * IntentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IntentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements IntentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  IntentRepository,
} from "@klarwatt/services/contacts";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { IntentRepositoryDdb } from "./intent-repository.ddb.js";

/**
 * IntentRepositoryAdapter
 *
 * Implements IntentRepository port for infrastructure layer.
 */
export class IntentRepositoryAdapter implements IntentRepository {
  private readonly ddb: IntentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new IntentRepositoryDdb(this.dynamoClient);
  }

  async classifyContactIntent(input: Parameters<IntentRepository['classifyContactIntent']>[0]): Promise<Awaited<ReturnType<IntentRepository['classifyContactIntent']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.classifyContactIntent(input);
  }
}
