/**
 * EstimatedReadCorrection Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consumption
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/consumption.openapi.types.js";
import { schemas } from "../schemas/consumption.schemas.js";

/**
 * Entity: EstimatedReadCorrectionEntity
 * Description: Represents the EstimatedReadCorrection domain model.
 * Source: schemas.EstimatedReadCorrection
 * Type: Domain Entity (API)
 */
export const EstimatedReadCorrectionEntitySchema = schemas.EstimatedReadCorrection;
export type EstimatedReadCorrectionEntity = components["schemas"]["EstimatedReadCorrection"];
