/**
 * ExecuteApproveAutomationRelease - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteApproveAutomationRelease Use Case
 *
 * DDD: Application use case for create Release.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ApproveAutomationReleaseInput, ApproveAutomationReleaseOutput } from "../dto/release.dto";
import type { ExecutionContextService, IdGeneratorService } from "@klarwatt/services/_shared/index.js";
import type { ReleaseRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteApproveAutomationRelease {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly release: ReleaseRepository
  ) {}

  async execute(input: ApproveAutomationReleaseInput): Promise<ApproveAutomationReleaseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cplId();

    // All field names extracted from OpenAPI spec: affectedIntents, approvedBy, capability, changeSummary, version
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.approvedBy) {
      throw new ValidationError("approvedBy is required");
    }
    if (!input.capability) {
      throw new ValidationError("capability is required");
    }
    if (!input.version) {
      throw new ValidationError("version is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (compliance domain)
    const entityId = this.idGenerator.cplId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.release.approveAutomationRelease({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as ApproveAutomationReleaseOutput;
  }
}
