/**
 * Contacts DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Contacts Domain Module - Composition root
 *
 * DDD: Composition root for contacts domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AdvisorCorrectionRepositoryAdapter,
  ContactRepositoryAdapter,
  ContextRepositoryAdapter,
  HandoverRepositoryAdapter,
  IntentRepositoryAdapter,
} from "@klarwatt/adapters/contacts";
import { getIdGeneratorService } from "@klarwatt/adapters";
import type { AdapterDynamoDBClient } from "@klarwatt/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteClassifyContactIntent,
  ExecuteEscalateToAdvisor,
  ExecuteGetAccountContext,
  ExecuteGetContactSession,
  ExecuteListContactSessions,
  ExecuteOpenContactSession,
  ExecuteRecordAdvisorCorrection,
} from "@klarwatt/services/contacts/usecases";
// Ports (interfaces)
import type {
  AdvisorCorrectionRepository,
  ContactRepository,
  ContextRepository,
  HandoverRepository,
  IntentRepository,
} from "@klarwatt/services/contacts/ports";

export interface ContactsDomainModule {
  repos: {
    advisorCorrections: AdvisorCorrectionRepository;
    contacts: ContactRepository;
    contexts: ContextRepository;
    handovers: HandoverRepository;
    intents: IntentRepository;
  };
  useCases: {
    advisorCorrections: {
      get: ExecuteRecordAdvisorCorrection;
    };
    contacts: {
      get: ExecuteGetContactSession;
      list: ExecuteListContactSessions;
    };
    contexts: {
      get: ExecuteGetAccountContext;
    };
    handovers: {
      get: ExecuteEscalateToAdvisor;
    };
    intents: {
      get: ExecuteClassifyContactIntent;
    };
  };
}

export function buildContactsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ContactsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      advisorCorrections?: AdvisorCorrectionRepository;
      contacts?: ContactRepository;
      contexts?: ContextRepository;
      handovers?: HandoverRepository;
      intents?: IntentRepository;
    } = {};

    obj.advisorCorrections = new AdvisorCorrectionRepositoryAdapter(dynamoClient);
    obj.contacts = new ContactRepositoryAdapter(dynamoClient);
    obj.contexts = new ContextRepositoryAdapter(dynamoClient);
    obj.handovers = new HandoverRepositoryAdapter(dynamoClient);
    obj.intents = new IntentRepositoryAdapter(dynamoClient);
    return {
      advisorCorrections: obj.advisorCorrections!,
      contacts: obj.contacts!,
      contexts: obj.contexts!,
      handovers: obj.handovers!,
      intents: obj.intents!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    advisorCorrections: {
      get: new ExecuteRecordAdvisorCorrection(executionContext, idGenerator, repos.advisorCorrections),
    },
    contacts: {
      get: new ExecuteGetContactSession(executionContext, idGenerator, repos.contacts),
      list: new ExecuteListContactSessions(executionContext, idGenerator, repos.contacts),
    },
    contexts: {
      get: new ExecuteGetAccountContext(executionContext, idGenerator, repos.contexts),
    },
    handovers: {
      get: new ExecuteEscalateToAdvisor(executionContext, idGenerator, repos.handovers),
    },
    intents: {
      get: new ExecuteClassifyContactIntent(executionContext, idGenerator, repos.intents),
    },
  };
  return { repos, useCases: useCases as ContactsDomainModule["useCases"] };
}
