/**
 * CohortRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cohorts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CohortRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CohortRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CohortRepository,
} from "@klarwatt/services/cohorts";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CohortRepositoryDdb } from "./cohort-repository.ddb.js";

/**
 * CohortRepositoryAdapter
 *
 * Implements CohortRepository port for infrastructure layer.
 */
export class CohortRepositoryAdapter implements CohortRepository {
  private readonly ddb: CohortRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CohortRepositoryDdb(this.dynamoClient);
  }

  async listPilotCohorts(input: Parameters<CohortRepository['listPilotCohorts']>[0]): Promise<Awaited<ReturnType<CohortRepository['listPilotCohorts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listPilotCohorts(input);
  }

  async createPilotCohort(input: Parameters<CohortRepository['createPilotCohort']>[0]): Promise<Awaited<ReturnType<CohortRepository['createPilotCohort']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createPilotCohort(input);
  }
}
