/**
 * Repository interface for EstimatedReadCorrection
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: consumption
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  EstimatedReadCorrectionEntity
} from "../models/estimated-read-correction.entity.js";
import type {
  ListEstimatedReadCorrectionsParams
} from "../types/index.js";
/**
 * EstimatedReadCorrectionRepository Interface
 */
export interface EstimatedReadCorrectionRepository extends ReadRepository<EstimatedReadCorrectionEntity, string, ListEstimatedReadCorrectionsParams> {

}
