/**
 * Handlers for Recommendation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advice
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AdviceDomainModule } from "../dependencies/advice-ddd.dependencies.js";
import type { ListAdviceRecommendationsInput } from "@klarwatt/services/advice";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/advice/recommendations
 * Operation: listAdviceRecommendations
 */
export async function listAdviceRecommendations(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { accountId?: string | string[], cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AdviceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAdviceRecommendationsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.recommendations.list.execute(input);
  return reply.code(200).send(result);
}


