/**
 * Routes for Record
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consent
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { captureConsent, listConsentRecords } from "../handlers/record.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function recordRoutes(fastify: FastifyInstance) {
  // POST /v1/consent/records (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/consent/records",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConsentDependenciesForRequest();
        await captureConsent(request, reply, deps);
      });
    }
  );


  // GET /v1/consent/records (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/consent/records",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConsentDependenciesForRequest();
        await listConsentRecords(request, reply, deps);
      });
    }
  );


}
