/**
 * Consumption DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consumption
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Consumption Domain Module - Composition root
 *
 * DDD: Composition root for consumption domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DataDefectRepositoryAdapter,
  EstimatedReadCorrectionRepositoryAdapter,
  ExplanationRepositoryAdapter,
} from "@klarwatt/adapters/consumption";
import { getIdGeneratorService } from "@klarwatt/adapters";
import type { AdapterDynamoDBClient } from "@klarwatt/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteExplainConsumptionChange,
  ExecuteListEstimatedReadCorrections,
  ExecuteRaiseDataDefectReport,
} from "@klarwatt/services/consumption/usecases";
// Ports (interfaces)
import type {
  DataDefectRepository,
  EstimatedReadCorrectionRepository,
  ExplanationRepository,
} from "@klarwatt/services/consumption/ports";

export interface ConsumptionDomainModule {
  repos: {
    dataDefects: DataDefectRepository;
    estimatedReadCorrections: EstimatedReadCorrectionRepository;
    explanations: ExplanationRepository;
  };
  useCases: {
    dataDefects: {
      get: ExecuteRaiseDataDefectReport;
    };
    estimatedReadCorrections: {
      list: ExecuteListEstimatedReadCorrections;
    };
    explanations: {
      get: ExecuteExplainConsumptionChange;
    };
  };
}

export function buildConsumptionDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ConsumptionDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      dataDefects?: DataDefectRepository;
      estimatedReadCorrections?: EstimatedReadCorrectionRepository;
      explanations?: ExplanationRepository;
    } = {};

    obj.dataDefects = new DataDefectRepositoryAdapter(dynamoClient);
    obj.estimatedReadCorrections = new EstimatedReadCorrectionRepositoryAdapter(dynamoClient);
    obj.explanations = new ExplanationRepositoryAdapter(dynamoClient);
    return {
      dataDefects: obj.dataDefects!,
      estimatedReadCorrections: obj.estimatedReadCorrections!,
      explanations: obj.explanations!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    dataDefects: {
      get: new ExecuteRaiseDataDefectReport(executionContext, idGenerator, repos.dataDefects),
    },
    estimatedReadCorrections: {
      list: new ExecuteListEstimatedReadCorrections(executionContext, idGenerator, repos.estimatedReadCorrections),
    },
    explanations: {
      get: new ExecuteExplainConsumptionChange(executionContext, idGenerator, repos.explanations),
    },
  };
  return { repos, useCases: useCases as ConsumptionDomainModule["useCases"] };
}
