/**
 * EvidencePack DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EvidencePack DTOs
 *
 * DDD: Application DTOs for EvidencePack use cases.
 */

import type { GenerateEvidencePackRequestInput } from "@klarwatt/core/compliance/types";

export type GenerateEvidencePackInput = GenerateEvidencePackRequestInput;

export type GenerateEvidencePackOutput = {};
