/**
 * UnbundlingCheck DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * UnbundlingCheck DTOs
 *
 * DDD: Application DTOs for UnbundlingCheck use cases.
 */

import type { ListUnbundlingChecksParams } from "@klarwatt/core/compliance/types";

export type ListUnbundlingChecksInput = ListUnbundlingChecksParams;

export type ListUnbundlingChecksOutput = {};
