/**
 * Record DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consent
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Record DTOs
 *
 * DDD: Application DTOs for Record use cases.
 */

import type { CaptureConsentRequestInput, ListConsentRecordsParams } from "@klarwatt/core/consent/types";

export type ListConsentRecordsInput = ListConsentRecordsParams;

export type CaptureConsentInput = CaptureConsentRequestInput;

export type ListConsentRecordsOutput = {};

export type CaptureConsentOutput = {};
