/**
 * PaymentPlan Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: resolutions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { PaymentPlanEntity } from "@klarwatt/core/resolutions/models/index.js";
import { resolutionsSchemas } from "@klarwatt/core/resolutions";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "res";

export function createPaymentPlan(overrides: Partial<PaymentPlanEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    accountId: overrides.accountId ?? faker.string.uuid(),
    status: overrides.status ?? "proposed",
    ...overrides,
  };

  return resolutionsSchemas.PaymentPlan.parse(raw);
}

export function paymentPlanBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createPaymentPlan(overrides));
}
