/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consent
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./purpose-repository.ddb.js";
export * from "./record-repository.ddb.js";
export * from "./withdrawal-repository.ddb.js";
export * from "./purpose-repository.adapter.js";
export * from "./record-repository.adapter.js";
export * from "./withdrawal-repository.adapter.js";
