/**
 * PurposeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consent
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PurposeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PurposeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PurposeRepository,
} from "@klarwatt/services/consent";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PurposeRepositoryDdb } from "./purpose-repository.ddb.js";

/**
 * PurposeRepositoryAdapter
 *
 * Implements PurposeRepository port for infrastructure layer.
 */
export class PurposeRepositoryAdapter implements PurposeRepository {
  private readonly ddb: PurposeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PurposeRepositoryDdb(this.dynamoClient);
  }

  async listDataPurposes(input: Parameters<PurposeRepository['listDataPurposes']>[0]): Promise<Awaited<ReturnType<PurposeRepository['listDataPurposes']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDataPurposes(input);
  }
}
