/**
 * RecordRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consent
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RecordRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RecordRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RecordRepository,
} from "@klarwatt/services/consent";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RecordRepositoryDdb } from "./record-repository.ddb.js";

/**
 * RecordRepositoryAdapter
 *
 * Implements RecordRepository port for infrastructure layer.
 */
export class RecordRepositoryAdapter implements RecordRepository {
  private readonly ddb: RecordRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RecordRepositoryDdb(this.dynamoClient);
  }

  async listConsentRecords(input: Parameters<RecordRepository['listConsentRecords']>[0]): Promise<Awaited<ReturnType<RecordRepository['listConsentRecords']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listConsentRecords(input);
  }

  async captureConsent(input: Parameters<RecordRepository['captureConsent']>[0]): Promise<Awaited<ReturnType<RecordRepository['captureConsent']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.captureConsent(input);
  }
}
