/**
 * WithdrawalRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consent
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * WithdrawalRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements WithdrawalRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  WithdrawalRepository,
} from "@klarwatt/services/consent";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { WithdrawalRepositoryDdb } from "./withdrawal-repository.ddb.js";

/**
 * WithdrawalRepositoryAdapter
 *
 * Implements WithdrawalRepository port for infrastructure layer.
 */
export class WithdrawalRepositoryAdapter implements WithdrawalRepository {
  private readonly ddb: WithdrawalRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new WithdrawalRepositoryDdb(this.dynamoClient);
  }

  async withdrawConsent(input: Parameters<WithdrawalRepository['withdrawConsent']>[0]): Promise<Awaited<ReturnType<WithdrawalRepository['withdrawConsent']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.withdrawConsent(input);
  }
}
