/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import {
  getCoreTableName,
  getBaseTableName,
  getAnalyticsTableName,
} from "@klarwatt/adapters";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health check (public - no auth required)
  fastify.get("/health", { config: { scope: "public" } }, async () => {
    try {
      const coreTable = getCoreTableName();
      const baseTable = getBaseTableName();
      const analyticsTable = getAnalyticsTableName();
      return {
        status: "ok",
        database: "dynamodb",
        tables: {
          core: coreTable,
          base: baseTable,
          analytics: analyticsTable,
        },
      };
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      fastify.log.warn({ error: errorMessage }, "Health check failed");
      return { status: "error", database: "disconnected", error: errorMessage };
    }
  });

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "advice", "cohorts", "complaints", "compliance", "consent", "consumption", "contacts", "identity", "resolutions", "vulnerability"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      advice: [{ method: "GET", path: "/v1/advice/recommendations" }],
      cohorts: [{ method: "GET", path: "/v1/cohorts" }, { method: "POST", path: "/v1/cohorts" }, { method: "GET", path: "/v1/cohorts/:cohortId/metrics" }, { method: "POST", path: "/v1/cohorts/:cohortId/decision" }],
      complaints: [{ method: "GET", path: "/v1/complaints" }, { method: "POST", path: "/v1/complaints" }],
      compliance: [{ method: "GET", path: "/v1/compliance/unbundling-checks" }, { method: "GET", path: "/v1/compliance/releases" }, { method: "POST", path: "/v1/compliance/releases" }, { method: "POST", path: "/v1/compliance/evidence-packs" }],
      consent: [{ method: "GET", path: "/v1/consent/purposes" }, { method: "GET", path: "/v1/consent/records" }, { method: "POST", path: "/v1/consent/records" }, { method: "POST", path: "/v1/consent/records/:consentId/withdrawal" }],
      consumption: [{ method: "POST", path: "/v1/consumption/explanations" }, { method: "GET", path: "/v1/consumption/estimated-read-corrections" }, { method: "POST", path: "/v1/consumption/data-defects" }],
      contacts: [{ method: "GET", path: "/v1/contacts" }, { method: "POST", path: "/v1/contacts" }, { method: "GET", path: "/v1/contacts/:sessionId" }, { method: "POST", path: "/v1/contacts/:sessionId/intents" }, { method: "POST", path: "/v1/contacts/:sessionId/handover" }, { method: "POST", path: "/v1/contacts/:sessionId/advisor-correction" }, { method: "GET", path: "/v1/accounts/:accountId/context" }],
      identity: [],
      resolutions: [{ method: "POST", path: "/v1/resolutions" }, { method: "POST", path: "/v1/resolutions/payment-plans" }],
      vulnerability: [{ method: "GET", path: "/v1/vulnerability/flags" }, { method: "POST", path: "/v1/vulnerability/flags" }, { method: "GET", path: "/v1/vulnerability/gate-policy" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "All routes (except /health and /routes) require JWT token in Authorization header",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Replace :orgId with actual organization ID. All domain routes require authentication.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
