/**
 * ExecuteExecuteResolution - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: resolutions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteExecuteResolution Use Case
 *
 * DDD: Application use case for create Resolution.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ExecuteResolutionInput, ExecuteResolutionOutput } from "../dto/resolution.dto";
import type { ExecutionContextService, IdGeneratorService } from "@klarwatt/services/_shared/index.js";
import type { ResolutionRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteExecuteResolution {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly resolution: ResolutionRepository
  ) {}

  async execute(input: ExecuteResolutionInput): Promise<ExecuteResolutionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.resId();

    // All field names extracted from OpenAPI spec: actionType, parameters, sessionId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.actionType) {
      throw new ValidationError("actionType is required");
    }
    if (!input.sessionId) {
      throw new ValidationError("sessionId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (resolutions domain)
    const entityId = this.idGenerator.resId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.resolution.executeResolution({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as ExecuteResolutionOutput;
  }
}
