/**
 * GetContactSession handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getContactSession } from "@klarwatt/api-server/domains/contacts/handlers";
import type { ContactsDDDDependencies } from "@klarwatt/api-server/domains/contacts";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@klarwatt/tests/shared";
import { CONTACTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetContactSession", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ContactsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ContactsDDDDependencies>(
      CONTACTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetContactSession, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { sessionId: entity.id };

    await getContactSession(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetContactSession.execute).toHaveBeenCalledWith(expect.objectContaining({ sessionId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { sessionId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetContactSession, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getContactSession(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
