/**
 * DataDefect DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consumption
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataDefect DTOs
 *
 * DDD: Application DTOs for DataDefect use cases.
 */

import type { RaiseDataDefectReportRequestInput } from "@klarwatt/core/consumption/types";

export type RaiseDataDefectReportInput = RaiseDataDefectReportRequestInput;

export type RaiseDataDefectReportOutput = {};
