/**
 * Explanation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consumption
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Explanation DTOs
 *
 * DDD: Application DTOs for Explanation use cases.
 */

import type { ExplainConsumptionChangeRequestInput } from "@klarwatt/core/consumption/types";

export type ExplainConsumptionChangeInput = ExplainConsumptionChangeRequestInput;

export type ExplainConsumptionChangeOutput = {};
