/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cohorts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Cohorts Domain Use Cases
 * 
 * List of all use case names for the cohorts domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const COHORTS_USE_CASES = [
  "executeCreatePilotCohort",
  "executeDecideCohortOutcome",
  "executeGetCohortMetrics",
  "executeListPilotCohorts"
] as const;
