/**
 * PaymentPlan DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: resolutions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PaymentPlan DTOs
 *
 * DDD: Application DTOs for PaymentPlan use cases.
 */

import type { ProposePaymentPlanRequestInput } from "@klarwatt/core/resolutions/types";

export type ProposePaymentPlanInput = ProposePaymentPlanRequestInput;

export type ProposePaymentPlanOutput = {};
