/**
 * Resolution DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: resolutions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Resolution DTOs
 *
 * DDD: Application DTOs for Resolution use cases.
 */

import type { ExecuteResolutionRequestInput } from "@klarwatt/core/resolutions/types";

export type ExecuteResolutionInput = ExecuteResolutionRequestInput;

export type ExecuteResolutionOutput = {};
