/**
 * ListEstimatedReadCorrections handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consumption
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listEstimatedReadCorrections } from "@klarwatt/api-server/domains/consumption/handlers";
import type { ConsumptionDDDDependencies } from "@klarwatt/api-server/domains/consumption";
import { createEstimatedReadCorrection as createEstimatedReadCorrectionEntity } from "@klarwatt/factories/consumption";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@klarwatt/tests/shared";
import { CONSUMPTION_USE_CASES } from "../__factories__/use-cases.js";

describe("ListEstimatedReadCorrections", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ConsumptionDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ConsumptionDDDDependencies>(
      CONSUMPTION_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createEstimatedReadCorrectionEntity({ orgId }),
      createEstimatedReadCorrectionEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListEstimatedReadCorrections, "execute").mockResolvedValue(useCaseResult);

    await listEstimatedReadCorrections(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListEstimatedReadCorrections.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
