/**
 * ExplainConsumptionChange handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consumption
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { explainConsumptionChange } from "@klarwatt/api-server/domains/consumption/handlers";
import type { ConsumptionDDDDependencies } from "@klarwatt/api-server/domains/consumption";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@klarwatt/tests/shared";
import { CONSUMPTION_USE_CASES } from "../__factories__/use-cases.js";

describe("ExplainConsumptionChange", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ConsumptionDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ConsumptionDDDDependencies>(
      CONSUMPTION_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeExplainConsumptionChange, "execute").mockResolvedValue(useCaseResult);

    await explainConsumptionChange(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeExplainConsumptionChange.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
