/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @klarwatt/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@klarwatt/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@klarwatt/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@klarwatt/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@klarwatt/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@klarwatt/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _advice from "./advice/index.js";
import * as _cohorts from "./cohorts/index.js";
import * as _complaints from "./complaints/index.js";
import * as _compliance from "./compliance/index.js";
import * as _consent from "./consent/index.js";
import * as _consumption from "./consumption/index.js";
import * as _contacts from "./contacts/index.js";
import * as _identity from "./identity/index.js";
import * as _resolutions from "./resolutions/index.js";
import * as _vulnerability from "./vulnerability/index.js";

// Export as namespaces
export const _shared = __shared;
export const advice = _advice;
export const cohorts = _cohorts;
export const complaints = _complaints;
export const compliance = _compliance;
export const consent = _consent;
export const consumption = _consumption;
export const contacts = _contacts;
export const identity = _identity;
export const resolutions = _resolutions;
export const vulnerability = _vulnerability;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@klarwatt/core"; activity.types.*
//   - Direct exports: import * from "@klarwatt/core/activity/types/index.js"
//   - Direct exports: import * from "@klarwatt/core/activity/repositories/index.js"
//   - Direct exports: import * from "@klarwatt/core/activity/models/index.js"
//   - Direct exports: import * from "@klarwatt/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Advice Service
export { schemas as AdviceSchemas } from "./advice/schemas/advice.schemas.js";

// Cohorts Service
export { schemas as CohortsSchemas } from "./cohorts/schemas/cohorts.schemas.js";

// Complaints Service
export { schemas as ComplaintsSchemas } from "./complaints/schemas/complaints.schemas.js";

// Compliance Service
export { schemas as ComplianceSchemas } from "./compliance/schemas/compliance.schemas.js";

// Consent Service
export { schemas as ConsentSchemas } from "./consent/schemas/consent.schemas.js";

// Consumption Service
export { schemas as ConsumptionSchemas } from "./consumption/schemas/consumption.schemas.js";

// Contacts Service
export { schemas as ContactsSchemas } from "./contacts/schemas/contacts.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Resolutions Service
export { schemas as ResolutionsSchemas } from "./resolutions/schemas/resolutions.schemas.js";

// Vulnerability Service
export { schemas as VulnerabilitySchemas } from "./vulnerability/schemas/vulnerability.schemas.js";

