/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advice
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Advice Domain Use Cases
 * 
 * List of all use case names for the advice domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const ADVICE_USE_CASES = [
  "executeListAdviceRecommendations"
] as const;
