/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Contacts Domain Use Cases
 * 
 * List of all use case names for the contacts domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const CONTACTS_USE_CASES = [
  "executeClassifyContactIntent",
  "executeEscalateToAdvisor",
  "executeGetAccountContext",
  "executeGetContactSession",
  "executeListContactSessions",
  "executeOpenContactSession",
  "executeRecordAdvisorCorrection"
] as const;
