/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/consumption/explanations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain Consumption Change */
        post: operations["explainConsumptionChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/consumption/estimated-read-corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Estimated Read Corrections */
        get: operations["listEstimatedReadCorrections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/consumption/data-defects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Raise Data Defect Report */
        post: operations["raiseDataDefectReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        MeteringGranularity: "monthly_total" | "daily" | "hourly" | "half_hourly";
        ConsumptionExplanationRequest: {
            accountId: string;
            meterPointId: string;
            /** @example 2026-01 */
            subjectPeriod: string;
            /** @example 2025-01 */
            comparisonPeriod: string;
            /** @enum {string} */
            requestedGranularity?: "monthly_total" | "daily" | "hourly" | "half_hourly";
            purposeId?: string;
        };
        Money: {
            /** Format: double */
            amount: number;
            /** @example EUR */
            currency: string;
        };
        ExplanationDriver: {
            /** @enum {string} */
            driver: "weather_and_degree_days" | "consumption_change" | "tariff_price_change" | "network_charge_change" | "standing_charge" | "estimated_read_correction" | "billing_period_length" | "tax_or_levy_change";
            contributionAmount: {
                /** Format: double */
                amount: number;
                /** @example EUR */
                currency: string;
            };
            /** Format: float */
            contributionPercent?: number;
            plainLanguage?: string;
            evidenceReference?: string;
        };
        ConsumptionExplanation: {
            accountId: string;
            meterPointId?: string;
            subjectPeriod: string;
            comparisonPeriod?: string;
            totalChange: {
                /** Format: double */
                amount: number;
                /** @example EUR */
                currency: string;
            };
            drivers: {
                /** @enum {string} */
                driver: "weather_and_degree_days" | "consumption_change" | "tariff_price_change" | "network_charge_change" | "standing_charge" | "estimated_read_correction" | "billing_period_length" | "tax_or_levy_change";
                contributionAmount: {
                    /** Format: double */
                    amount: number;
                    /** @example EUR */
                    currency: string;
                };
                /** Format: float */
                contributionPercent?: number;
                plainLanguage?: string;
                evidenceReference?: string;
            }[];
            /** @enum {string} */
            granularityUsed?: "monthly_total" | "daily" | "hourly" | "half_hourly";
            estimatedReadDisclosed?: boolean;
            /** Format: float */
            unexplainedResidualPercent?: number;
            /** Format: float */
            confidence?: number;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        ConsumptionExplanationResponse: {
            data: {
                accountId: string;
                meterPointId?: string;
                subjectPeriod: string;
                comparisonPeriod?: string;
                totalChange: {
                    /** Format: double */
                    amount: number;
                    /** @example EUR */
                    currency: string;
                };
                drivers: {
                    /** @enum {string} */
                    driver: "weather_and_degree_days" | "consumption_change" | "tariff_price_change" | "network_charge_change" | "standing_charge" | "estimated_read_correction" | "billing_period_length" | "tax_or_levy_change";
                    contributionAmount: {
                        /** Format: double */
                        amount: number;
                        /** @example EUR */
                        currency: string;
                    };
                    /** Format: float */
                    contributionPercent?: number;
                    plainLanguage?: string;
                    evidenceReference?: string;
                }[];
                /** @enum {string} */
                granularityUsed?: "monthly_total" | "daily" | "hourly" | "half_hourly";
                estimatedReadDisclosed?: boolean;
                /** Format: float */
                unexplainedResidualPercent?: number;
                /** Format: float */
                confidence?: number;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        EstimatedReadCorrection: {
            id: string;
            meterPointId: string;
            /** Format: double */
            estimatedValueKwh?: number;
            /** Format: double */
            actualValueKwh?: number;
            billingPeriodsAffected?: string[];
            monetaryAdjustment?: {
                /** Format: double */
                amount: number;
                /** @example EUR */
                currency: string;
            };
            /** Format: date-time */
            correctedAt: string;
            disclosedToCustomer?: boolean;
        };
        EstimatedReadCorrectionListResponse: {
            data: {
                items: {
                    id: string;
                    meterPointId: string;
                    /** Format: double */
                    estimatedValueKwh?: number;
                    /** Format: double */
                    actualValueKwh?: number;
                    billingPeriodsAffected?: string[];
                    monetaryAdjustment?: {
                        /** Format: double */
                        amount: number;
                        /** @example EUR */
                        currency: string;
                    };
                    /** Format: date-time */
                    correctedAt: string;
                    disclosedToCustomer?: boolean;
                }[];
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        DataDefectReportCreate: {
            meterPointId: string;
            sessionId?: string;
            /** @enum {string} */
            defectType: "missing_interval_data" | "implausible_read" | "persistent_estimation" | "register_mismatch" | "tariff_mapping_error" | "settlement_discrepancy";
            description: string;
        };
        DataDefectReport: {
            id: string;
            meterPointId: string;
            sessionId?: string;
            defectType: string;
            /** @enum {string} */
            status: "raised" | "accepted" | "fixed" | "rejected";
            description?: string;
            /** Format: date-time */
            raisedAt?: string;
        };
        DataDefectReportResponse: {
            data: {
                id: string;
                meterPointId: string;
                sessionId?: string;
                defectType: string;
                /** @enum {string} */
                status: "raised" | "accepted" | "fixed" | "rejected";
                description?: string;
                /** Format: date-time */
                raisedAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /** @description Opaque keyset cursor for list pages. */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    explainConsumptionChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    accountId: string;
                    meterPointId: string;
                    /** @example 2026-01 */
                    subjectPeriod: string;
                    /** @example 2025-01 */
                    comparisonPeriod: string;
                    /** @enum {string} */
                    requestedGranularity?: "monthly_total" | "daily" | "hourly" | "half_hourly";
                    purposeId?: string;
                };
            };
        };
        responses: {
            /** @description Quantified driver decomposition in plain language */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            accountId: string;
                            meterPointId?: string;
                            subjectPeriod: string;
                            comparisonPeriod?: string;
                            totalChange: {
                                /** Format: double */
                                amount: number;
                                /** @example EUR */
                                currency: string;
                            };
                            drivers: {
                                /** @enum {string} */
                                driver: "weather_and_degree_days" | "consumption_change" | "tariff_price_change" | "network_charge_change" | "standing_charge" | "estimated_read_correction" | "billing_period_length" | "tax_or_levy_change";
                                contributionAmount: {
                                    /** Format: double */
                                    amount: number;
                                    /** @example EUR */
                                    currency: string;
                                };
                                /** Format: float */
                                contributionPercent?: number;
                                plainLanguage?: string;
                                evidenceReference?: string;
                            }[];
                            /** @enum {string} */
                            granularityUsed?: "monthly_total" | "daily" | "hourly" | "half_hourly";
                            estimatedReadDisclosed?: boolean;
                            /** Format: float */
                            unexplainedResidualPercent?: number;
                            /** Format: float */
                            confidence?: number;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Requested granularity exceeds the purpose ceiling without consent */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listEstimatedReadCorrections: {
        parameters: {
            query?: {
                /** @description Opaque keyset cursor for list pages. */
                cursor?: string;
                /** @description Page size. */
                limit?: number;
                meterPointId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estimated versus actual read corrections affecting bills */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                meterPointId: string;
                                /** Format: double */
                                estimatedValueKwh?: number;
                                /** Format: double */
                                actualValueKwh?: number;
                                billingPeriodsAffected?: string[];
                                monetaryAdjustment?: {
                                    /** Format: double */
                                    amount: number;
                                    /** @example EUR */
                                    currency: string;
                                };
                                /** Format: date-time */
                                correctedAt: string;
                                disclosedToCustomer?: boolean;
                            }[];
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    raiseDataDefectReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    meterPointId: string;
                    sessionId?: string;
                    /** @enum {string} */
                    defectType: "missing_interval_data" | "implausible_read" | "persistent_estimation" | "register_mismatch" | "tariff_mapping_error" | "settlement_discrepancy";
                    description: string;
                };
            };
        };
        responses: {
            /** @description Metering data defect raised to billing operations as a work item */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            meterPointId: string;
                            sessionId?: string;
                            defectType: string;
                            /** @enum {string} */
                            status: "raised" | "accepted" | "fixed" | "rejected";
                            description?: string;
                            /** Format: date-time */
                            raisedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
