/**
 * Handlers for Cohort
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cohorts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CohortsDomainModule } from "../dependencies/cohorts-ddd.dependencies.js";
import type { CreatePilotCohortInput, ListPilotCohortsInput } from "@klarwatt/services/cohorts";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/cohorts
 * Operation: listPilotCohorts
 */
export async function listPilotCohorts(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CohortsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListPilotCohortsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.cohorts.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/cohorts
 * Operation: createPilotCohort
 */
export async function createPilotCohort(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CohortsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreatePilotCohortInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.cohorts.create.execute(input);
  return reply.code(201).send(result);
}


