/**
 * Cohorts DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cohorts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Cohorts Domain Module - Composition root
 *
 * DDD: Composition root for cohorts domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CohortRepositoryAdapter,
  DecisionRepositoryAdapter,
  MetricRepositoryAdapter,
} from "@klarwatt/adapters/cohorts";
import { getIdGeneratorService } from "@klarwatt/adapters";
import type { AdapterDynamoDBClient } from "@klarwatt/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreatePilotCohort,
  ExecuteDecideCohortOutcome,
  ExecuteGetCohortMetrics,
  ExecuteListPilotCohorts,
} from "@klarwatt/services/cohorts/usecases";
// Ports (interfaces)
import type {
  CohortRepository,
  DecisionRepository,
  MetricRepository,
} from "@klarwatt/services/cohorts/ports";

export interface CohortsDomainModule {
  repos: {
    cohorts: CohortRepository;
    decisions: DecisionRepository;
    metrics: MetricRepository;
  };
  useCases: {
    cohorts: {
      create: ExecuteCreatePilotCohort;
      list: ExecuteListPilotCohorts;
    };
    decisions: {
      get: ExecuteDecideCohortOutcome;
    };
    metrics: {
      get: ExecuteGetCohortMetrics;
    };
  };
}

export function buildCohortsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CohortsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      cohorts?: CohortRepository;
      decisions?: DecisionRepository;
      metrics?: MetricRepository;
    } = {};

    obj.cohorts = new CohortRepositoryAdapter(dynamoClient);
    obj.decisions = new DecisionRepositoryAdapter(dynamoClient);
    obj.metrics = new MetricRepositoryAdapter(dynamoClient);
    return {
      cohorts: obj.cohorts!,
      decisions: obj.decisions!,
      metrics: obj.metrics!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    cohorts: {
      create: new ExecuteCreatePilotCohort(executionContext, idGenerator, repos.cohorts),
      list: new ExecuteListPilotCohorts(executionContext, idGenerator, repos.cohorts),
    },
    decisions: {
      get: new ExecuteDecideCohortOutcome(executionContext, idGenerator, repos.decisions),
    },
    metrics: {
      get: new ExecuteGetCohortMetrics(executionContext, idGenerator, repos.metrics),
    },
  };
  return { repos, useCases: useCases as CohortsDomainModule["useCases"] };
}
