/**
 * ExecuteListPilotCohorts - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cohorts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPilotCohorts Use Case
 *
 * DDD: Application use case for list Cohort.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPilotCohortsInput, ListPilotCohortsOutput } from "../dto/cohort.dto";
import type { ExecutionContextService, IdGeneratorService } from "@klarwatt/services/_shared/index.js";
import type { CohortRepository } from "../ports";

export class ExecuteListPilotCohorts {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly cohort: CohortRepository
  ) {}

  async execute(input: ListPilotCohortsInput): Promise<ListPilotCohortsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cohId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.cohort.listPilotCohorts({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPilotCohortsOutput;
  }
}
