/**
 * ExecuteDecideCohortOutcome - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cohorts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDecideCohortOutcome Use Case
 *
 * DDD: Application use case for get Decision.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DecideCohortOutcomeInput, DecideCohortOutcomeOutput } from "../dto/decision.dto";
import type { ExecutionContextService, IdGeneratorService } from "@klarwatt/services/_shared/index.js";
import type { DecisionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteDecideCohortOutcome {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly decision: DecisionRepository
  ) {}

  async execute(input: DecideCohortOutcomeInput): Promise<DecideCohortOutcomeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cohId();

    // All field names extracted from OpenAPI spec: decidedBy, outcome, rationale
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).cohortId) {
      throw new ValidationError("cohortId is required");
    }
    const cohortId = (input as any).cohortId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.decision.decideCohortOutcome({ cohortId: cohortId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${cohortId}`);
    }

    return entity as DecideCohortOutcomeOutput;
  }
}
