/**
 * Routes for Cohort
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cohorts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createPilotCohort, listPilotCohorts } from "../handlers/cohort.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function cohortRoutes(fastify: FastifyInstance) {
  // POST /v1/cohorts (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/cohorts",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCohortsDependenciesForRequest();
        await createPilotCohort(request, reply, deps);
      });
    }
  );


  // GET /v1/cohorts (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/cohorts",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCohortsDependenciesForRequest();
        await listPilotCohorts(request, reply, deps);
      });
    }
  );


}
