/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cohorts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { cohortRoutes } from "./cohort.routes.js";
export { decisionRoutes } from "./decision.routes.js";
export { metricRoutes } from "./metric.routes.js";
