/**
 * Handlers for EvidencePack
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ComplianceDomainModule } from "../dependencies/compliance-ddd.dependencies.js";
import type { GenerateEvidencePackInput } from "@klarwatt/services/compliance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/compliance/evidence-packs
 * Operation: generateEvidencePack
 */
export async function generateEvidencePack(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ComplianceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GenerateEvidencePackInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.evidencePacks.get.execute(input);
  return reply.code(201).send(result);
}


