/**
 * Handlers for UnbundlingCheck
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ComplianceDomainModule } from "../dependencies/compliance-ddd.dependencies.js";
import type { ListUnbundlingChecksInput } from "@klarwatt/services/compliance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/compliance/unbundling-checks
 * Operation: listUnbundlingChecks
 */
export async function listUnbundlingChecks(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], verdict?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ComplianceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListUnbundlingChecksInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.unbundlingChecks.list.execute(input);
  return reply.code(200).send(result);
}


