/**
 * RecommendationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advice
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RecommendationRepository Port
 *
 * DDD: Application port for recommendationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListAdviceRecommendationsInput, ListAdviceRecommendationsOutput } from "../dto/recommendation.dto";
export interface RecommendationRepository {
  listAdviceRecommendations(input: ListAdviceRecommendationsInput): Promise<ListAdviceRecommendationsOutput>;
}

export type { ListAdviceRecommendationsInput, ListAdviceRecommendationsOutput } from "../dto/recommendation.dto";
