/**
 * Intent Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { IntentEntity } from "@klarwatt/core/contacts/models/index.js";
import { contactsSchemas } from "@klarwatt/core/contacts";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ctc";

export function createIntent(overrides: Partial<IntentEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    confidence: overrides.confidence ?? faker.number.int(),
    name: overrides.name ?? faker.person.fullName(),
    ...overrides,
  };

  return contactsSchemas.Intent.parse(raw);
}

export function intentBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createIntent(overrides));
}
