/**
 * ContactRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContactRepository Port
 *
 * DDD: Application port for contactrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetContactSessionInput, GetContactSessionOutput, ListContactSessionsInput, ListContactSessionsOutput, OpenContactSessionInput, OpenContactSessionOutput } from "../dto/contact.dto";
export interface ContactRepository {
  openContactSession(input: OpenContactSessionInput): Promise<OpenContactSessionOutput>;
  listContactSessions(input: ListContactSessionsInput): Promise<ListContactSessionsOutput>;
  getContactSession(input: GetContactSessionInput): Promise<GetContactSessionOutput>;
}

export type { GetContactSessionInput, GetContactSessionOutput, ListContactSessionsInput, ListContactSessionsOutput, OpenContactSessionInput, OpenContactSessionOutput } from "../dto/contact.dto";
