/**
 * ContextRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContextRepository Port
 *
 * DDD: Application port for contextrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetAccountContextInput, GetAccountContextOutput } from "../dto/context.dto";
export interface ContextRepository {
  getAccountContext(input: GetAccountContextInput): Promise<GetAccountContextOutput>;
}

export type { GetAccountContextInput, GetAccountContextOutput } from "../dto/context.dto";
