/**
 * HandoverRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HandoverRepository Port
 *
 * DDD: Application port for handoverrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { EscalateToAdvisorInput, EscalateToAdvisorOutput } from "../dto/handover.dto";
export interface HandoverRepository {
  escalateToAdvisor(input: EscalateToAdvisorInput): Promise<EscalateToAdvisorOutput>;
}

export type { EscalateToAdvisorInput, EscalateToAdvisorOutput } from "../dto/handover.dto";
