/**
 * ClassifyContactIntent handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { classifyContactIntent } from "@klarwatt/api-server/domains/contacts/handlers";
import type { ContactsDDDDependencies } from "@klarwatt/api-server/domains/contacts";
import { createIntent as createIntentEntity } from "@klarwatt/factories/contacts";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@klarwatt/tests/shared";
import { CONTACTS_USE_CASES } from "../__factories__/use-cases.js";

describe("ClassifyContactIntent", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ContactsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ContactsDDDDependencies>(
      CONTACTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createIntentEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeClassifyContactIntent, "execute").mockResolvedValue(useCaseResult);

    await classifyContactIntent(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeClassifyContactIntent.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
