/**
 * GetContext DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetAccountContextParams } from "@klarwatt/core/contacts";

export function createGetContextRequest(overrides: Partial<GetAccountContextParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
