/**
 * ExplanationRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consumption
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExplanationRepositoryDdb
 *
 * DDD: Infrastructure adapter for Explanation repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { ExplanationRepository } from "@klarwatt/services/consumption";

export class ExplanationRepositoryDdb implements ExplanationRepository {
  constructor(private readonly dynamoClient: any) {}

  async explainConsumptionChange(input: Parameters<ExplanationRepository['explainConsumptionChange']>[0]): Promise<Awaited<ReturnType<ExplanationRepository['explainConsumptionChange']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }
}
