/**
 * PurposeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consent
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PurposeRepository Port
 *
 * DDD: Application port for purposerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListDataPurposesInput, ListDataPurposesOutput } from "../dto/purpose.dto";
export interface PurposeRepository {
  listDataPurposes(input: ListDataPurposesInput): Promise<ListDataPurposesOutput>;
}

export type { ListDataPurposesInput, ListDataPurposesOutput } from "../dto/purpose.dto";
