/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildAdviceDomainModule } from "./advice/dependencies/advice-ddd.dependencies.js";
export { buildCohortsDomainModule } from "./cohorts/dependencies/cohorts-ddd.dependencies.js";
export { buildComplaintsDomainModule } from "./complaints/dependencies/complaints-ddd.dependencies.js";
export { buildComplianceDomainModule } from "./compliance/dependencies/compliance-ddd.dependencies.js";
export { buildConsentDomainModule } from "./consent/dependencies/consent-ddd.dependencies.js";
export { buildConsumptionDomainModule } from "./consumption/dependencies/consumption-ddd.dependencies.js";
export { buildContactsDomainModule } from "./contacts/dependencies/contacts-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildResolutionsDomainModule } from "./resolutions/dependencies/resolutions-ddd.dependencies.js";
export { buildVulnerabilityDomainModule } from "./vulnerability/dependencies/vulnerability-ddd.dependencies.js";

// Export all domain dependency types
export type { AdviceDomainModule } from "./advice/dependencies/advice-ddd.dependencies.js";
export type { CohortsDomainModule } from "./cohorts/dependencies/cohorts-ddd.dependencies.js";
export type { ComplaintsDomainModule } from "./complaints/dependencies/complaints-ddd.dependencies.js";
export type { ComplianceDomainModule } from "./compliance/dependencies/compliance-ddd.dependencies.js";
export type { ConsentDomainModule } from "./consent/dependencies/consent-ddd.dependencies.js";
export type { ConsumptionDomainModule } from "./consumption/dependencies/consumption-ddd.dependencies.js";
export type { ContactsDomainModule } from "./contacts/dependencies/contacts-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { ResolutionsDomainModule } from "./resolutions/dependencies/resolutions-ddd.dependencies.js";
export type { VulnerabilityDomainModule } from "./vulnerability/dependencies/vulnerability-ddd.dependencies.js";
