/**
 * Handlers for Complaint
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaints
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ComplaintsDomainModule } from "../dependencies/complaints-ddd.dependencies.js";
import type { ListComplaintsInput, RecogniseComplaintInput } from "@klarwatt/services/complaints";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/complaints
 * Operation: recogniseComplaint
 */
export async function recogniseComplaint(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ComplaintsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RecogniseComplaintInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.complaints.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/complaints
 * Operation: listComplaints
 */
export async function listComplaints(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], raisedIn?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ComplaintsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListComplaintsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.complaints.list.execute(input);
  return reply.code(200).send(result);
}


