/**
 * CohortRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cohorts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CohortRepository Port
 *
 * DDD: Application port for cohortrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreatePilotCohortInput, CreatePilotCohortOutput, ListPilotCohortsInput, ListPilotCohortsOutput } from "../dto/cohort.dto";
export interface CohortRepository {
  listPilotCohorts(input: ListPilotCohortsInput): Promise<ListPilotCohortsOutput>;
  createPilotCohort(input: CreatePilotCohortInput): Promise<CreatePilotCohortOutput>;
}

export type { CreatePilotCohortInput, CreatePilotCohortOutput, ListPilotCohortsInput, ListPilotCohortsOutput } from "../dto/cohort.dto";
