/**
 * ExecuteCaptureConsent - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consent
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCaptureConsent Use Case
 *
 * DDD: Application use case for get Record.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CaptureConsentInput, CaptureConsentOutput } from "../dto/record.dto";
import type { ExecutionContextService, IdGeneratorService } from "@klarwatt/services/_shared/index.js";
import type { RecordRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteCaptureConsent {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly record: RecordRepository
  ) {}

  async execute(input: CaptureConsentInput): Promise<CaptureConsentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cstId();

    // All field names extracted from OpenAPI spec: accountId, capturedVia, grantedGranularity, purposeId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).accountId) {
      throw new ValidationError("accountId is required");
    }
    const accountId = (input as any).accountId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.record.captureConsent({ accountId: accountId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${accountId}`);
    }

    return entity as CaptureConsentOutput;
  }
}
