/**
 * Handlers for EstimatedReadCorrection
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consumption
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ConsumptionDomainModule } from "../dependencies/consumption-ddd.dependencies.js";
import type { ListEstimatedReadCorrectionsInput } from "@klarwatt/services/consumption";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/consumption/estimated-read-corrections
 * Operation: listEstimatedReadCorrections
 */
export async function listEstimatedReadCorrections(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], meterPointId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ConsumptionDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListEstimatedReadCorrectionsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.estimatedReadCorrections.list.execute(input);
  return reply.code(200).send(result);
}


