/**
 * Handlers for Explanation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consumption
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ConsumptionDomainModule } from "../dependencies/consumption-ddd.dependencies.js";
import type { ExplainConsumptionChangeInput } from "@klarwatt/services/consumption";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/consumption/explanations
 * Operation: explainConsumptionChange
 */
export async function explainConsumptionChange(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ConsumptionDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ExplainConsumptionChangeInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.explanations.get.execute(input);
  return reply.code(200).send(result);
}


