/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@klarwatt/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@klarwatt/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@klarwatt/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _advice from "./advice/index.js";
import * as _cohorts from "./cohorts/index.js";
import * as _complaints from "./complaints/index.js";
import * as _compliance from "./compliance/index.js";
import * as _consent from "./consent/index.js";
import * as _consumption from "./consumption/index.js";
import * as _contacts from "./contacts/index.js";
import * as _identity from "./identity/index.js";
import * as _resolutions from "./resolutions/index.js";
import * as _vulnerability from "./vulnerability/index.js";

// Export as namespaces
export const advice = _advice;
export const cohorts = _cohorts;
export const complaints = _complaints;
export const compliance = _compliance;
export const consent = _consent;
export const consumption = _consumption;
export const contacts = _contacts;
export const identity = _identity;
export const resolutions = _resolutions;
export const vulnerability = _vulnerability;
