/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./advisor-correction/index.js";
export * from "./contact/index.js";
export * from "./context/index.js";
export * from "./handover/index.js";
export * from "./intent/index.js";
