/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: resolutions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Resolutions Domain Use Cases
 * 
 * List of all use case names for the resolutions domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const RESOLUTIONS_USE_CASES = [
  "executeExecuteResolution",
  "executeProposePaymentPlan"
] as const;
