/**
 * ExecuteExplainConsumptionChange - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consumption
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteExplainConsumptionChange Use Case
 *
 * DDD: Application use case for get Explanation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ExplainConsumptionChangeInput, ExplainConsumptionChangeOutput } from "../dto/explanation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@klarwatt/services/_shared/index.js";
import type { ExplanationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteExplainConsumptionChange {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly explanation: ExplanationRepository
  ) {}

  async execute(input: ExplainConsumptionChangeInput): Promise<ExplainConsumptionChangeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cnsId();

    // All field names extracted from OpenAPI spec: accountId, comparisonPeriod, meterPointId, purposeId, requestedGranularity, subjectPeriod
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).accountId) {
      throw new ValidationError("accountId is required");
    }
    const accountId = (input as any).accountId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.explanation.explainConsumptionChange({ accountId: accountId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${accountId}`);
    }

    return entity as ExplainConsumptionChangeOutput;
  }
}
