/**
 * ExecuteRaiseDataDefectReport - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consumption
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRaiseDataDefectReport Use Case
 *
 * DDD: Application use case for get DataDefect.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RaiseDataDefectReportInput, RaiseDataDefectReportOutput } from "../dto/data-defect.dto";
import type { ExecutionContextService, IdGeneratorService } from "@klarwatt/services/_shared/index.js";
import type { DataDefectRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRaiseDataDefectReport {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dataDefect: DataDefectRepository
  ) {}

  async execute(input: RaiseDataDefectReportInput): Promise<RaiseDataDefectReportOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cnsId();

    // All field names extracted from OpenAPI spec: defectType, description, meterPointId, sessionId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).meterPointId) {
      throw new ValidationError("meterPointId is required");
    }
    const meterpointId = (input as any).meterPointId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.dataDefect.raiseDataDefectReport({ meterPointId: meterpointId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${meterpointId}`);
    }

    return entity as RaiseDataDefectReportOutput;
  }
}
