/**
 * ExecuteListEstimatedReadCorrections - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consumption
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListEstimatedReadCorrections Use Case
 *
 * DDD: Application use case for list EstimatedReadCorrection.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListEstimatedReadCorrectionsInput, ListEstimatedReadCorrectionsOutput } from "../dto/estimated-read-correction.dto";
import type { ExecutionContextService, IdGeneratorService } from "@klarwatt/services/_shared/index.js";
import type { EstimatedReadCorrectionRepository } from "../ports";

export class ExecuteListEstimatedReadCorrections {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly estimatedReadCorrection: EstimatedReadCorrectionRepository
  ) {}

  async execute(input: ListEstimatedReadCorrectionsInput): Promise<ListEstimatedReadCorrectionsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cnsId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.estimatedReadCorrection.listEstimatedReadCorrections({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListEstimatedReadCorrectionsOutput;
  }
}
