/**
 * Routes for Context
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getAccountContext } from "../handlers/context.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function contextRoutes(fastify: FastifyInstance) {
  // GET /v1/accounts/{accountId}/context (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/accounts/:accountId/context",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { accountId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getContactsDependenciesForRequest();
        await getAccountContext(request, reply, deps);
      });
    }
  );


}
