/**
 * Routes for Intent
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { classifyContactIntent } from "../handlers/intent.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function intentRoutes(fastify: FastifyInstance) {
  // POST /v1/contacts/{sessionId}/intents (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/contacts/:sessionId/intents",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { sessionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getContactsDependenciesForRequest();
        await classifyContactIntent(request, reply, deps);
      });
    }
  );


}
