/**
 * DataDefectRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consumption
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataDefectRepository Port
 *
 * DDD: Application port for datadefectrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RaiseDataDefectReportInput, RaiseDataDefectReportOutput } from "../dto/data-defect.dto";
export interface DataDefectRepository {
  raiseDataDefectReport(input: RaiseDataDefectReportInput): Promise<RaiseDataDefectReportOutput>;
}

export type { RaiseDataDefectReportInput, RaiseDataDefectReportOutput } from "../dto/data-defect.dto";
