/**
 * ExecuteOpenContactSession - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteOpenContactSession Use Case
 *
 * DDD: Application use case for get Contact.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { OpenContactSessionInput, OpenContactSessionOutput } from "../dto/contact.dto";
import type { ExecutionContextService, IdGeneratorService } from "@klarwatt/services/_shared/index.js";
import type { ContactRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteOpenContactSession {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly contact: ContactRepository
  ) {}

  async execute(input: OpenContactSessionInput): Promise<OpenContactSessionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ctcId();

    // All field names extracted from OpenAPI spec: accountReference, channel, cohortId, declaredRole, meterPointId, purposeId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).cohortId) {
      throw new ValidationError("cohortId is required");
    }
    const cohortId = (input as any).cohortId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.contact.openContactSession({ cohortId: cohortId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${cohortId}`);
    }

    return entity as OpenContactSessionOutput;
  }
}
