/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consent
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Consent Domain Use Cases
 * 
 * List of all use case names for the consent domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const CONSENT_USE_CASES = [
  "executeCaptureConsent",
  "executeListConsentRecords",
  "executeListDataPurposes",
  "executeWithdrawConsent"
] as const;
