/**
 * Complaint DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaints
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Complaint DTOs
 *
 * DDD: Application DTOs for Complaint use cases.
 */

import type { ListComplaintsParams, RecogniseComplaintRequestInput } from "@klarwatt/core/complaints/types";

export type RecogniseComplaintInput = RecogniseComplaintRequestInput;

export type ListComplaintsInput = ListComplaintsParams;

export type RecogniseComplaintOutput = {};

export type ListComplaintsOutput = {};
