/**
 * ListRecommendation DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advice
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListAdviceRecommendationsParams } from "@klarwatt/core/advice";

export function createListRecommendationRequest(overrides: Partial<ListAdviceRecommendationsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
