/**
 * Handlers for Contact
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ContactsDomainModule } from "../dependencies/contacts-ddd.dependencies.js";
import type { GetContactSessionInput, ListContactSessionsInput, OpenContactSessionInput } from "@klarwatt/services/contacts";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/contacts
 * Operation: openContactSession
 */
export async function openContactSession(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ContactsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: OpenContactSessionInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.contacts.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/contacts
 * Operation: listContactSessions
 */
export async function listContactSessions(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], outcome?: string | string[], channel?: string | string[], vulnerabilityOnly?: string | string[], complaintClockRunning?: string | string[], escalatedOnly?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ContactsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListContactSessionsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.contacts.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/contacts/{sessionId}
 * Operation: getContactSession
 */
export async function getContactSession(
  request: FastifyRequest<{ Params: { sessionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ContactsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetContactSessionInput = {
    sessionId: request.params.sessionId,
  };
  const result = await deps.useCases.contacts.get.execute(input);
  return reply.code(200).send(result);
}


