/**
 * Handlers for Context
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ContactsDomainModule } from "../dependencies/contacts-ddd.dependencies.js";
import type { GetAccountContextInput } from "@klarwatt/services/contacts";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/accounts/{accountId}/context
 * Operation: getAccountContext
 */
export async function getAccountContext(
  request: FastifyRequest<{ Params: { accountId: string }; Querystring: { purposeId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ContactsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAccountContextInput = {
    accountId: request.params.accountId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.contexts.get.execute(input);
  return reply.code(200).send(result);
}


