/**
 * Handlers for Intent
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ContactsDomainModule } from "../dependencies/contacts-ddd.dependencies.js";
import type { ClassifyContactIntentInput } from "@klarwatt/services/contacts";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/contacts/{sessionId}/intents
 * Operation: classifyContactIntent
 */
export async function classifyContactIntent(
  request: FastifyRequest<{ Params: { sessionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ContactsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ClassifyContactIntentInput = {
    sessionId: request.params.sessionId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.intents.get.execute(input);
  return reply.code(200).send(result);
}


