/**
 * EvidencePackRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EvidencePackRepository Port
 *
 * DDD: Application port for evidencepackrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GenerateEvidencePackInput, GenerateEvidencePackOutput } from "../dto/evidence-pack.dto";
export interface EvidencePackRepository {
  generateEvidencePack(input: GenerateEvidencePackInput): Promise<GenerateEvidencePackOutput>;
}

export type { GenerateEvidencePackInput, GenerateEvidencePackOutput } from "../dto/evidence-pack.dto";
