/**
 * UnbundlingCheckRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * UnbundlingCheckRepository Port
 *
 * DDD: Application port for unbundlingcheckrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListUnbundlingChecksInput, ListUnbundlingChecksOutput } from "../dto/unbundling-check.dto";
export interface UnbundlingCheckRepository {
  listUnbundlingChecks(input: ListUnbundlingChecksInput): Promise<ListUnbundlingChecksOutput>;
}

export type { ListUnbundlingChecksInput, ListUnbundlingChecksOutput } from "../dto/unbundling-check.dto";
