/**
 * ListCohort DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cohorts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListPilotCohortsParams } from "@klarwatt/core/cohorts";

export function createListCohortRequest(overrides: Partial<ListPilotCohortsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
