/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/resolutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Resolution */
        post: operations["executeResolution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/resolutions/payment-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose Payment Plan */
        post: operations["proposePaymentPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ResolutionActionCreate: {
            sessionId: string;
            /** @enum {string} */
            actionType: "request_meter_reread" | "request_meter_inspection" | "tariff_eligibility_check" | "refer_network_fault" | "reissue_bill" | "update_contact_preference" | "send_explanation_summary";
            parameters?: {
                [key: string]: string;
            };
        };
        ResolutionAction: {
            id: string;
            sessionId: string;
            actionType: string;
            /** @enum {string} */
            status: "executed" | "queued" | "blocked_by_policy" | "failed";
            policyReference?: string;
            /** @enum {string} */
            targetSystem?: "billing" | "meter_data_management" | "collections" | "network_operator" | "crm";
            blockReason?: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        ResolutionActionResponse: {
            data: {
                id: string;
                sessionId: string;
                actionType: string;
                /** @enum {string} */
                status: "executed" | "queued" | "blocked_by_policy" | "failed";
                policyReference?: string;
                /** @enum {string} */
                targetSystem?: "billing" | "meter_data_management" | "collections" | "network_operator" | "crm";
                blockReason?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        Money: {
            /** Format: double */
            amount: number;
            /** @example EUR */
            currency: string;
        };
        PaymentPlanProposal: {
            accountId: string;
            instalmentAmount: {
                /** Format: double */
                amount: number;
                /** @example EUR */
                currency: string;
            };
            instalmentCount: number;
            affordabilityPolicyRef?: string;
            advisorReference: string;
        };
        PaymentPlan: {
            id: string;
            accountId: string;
            /** @enum {string} */
            status: "proposed" | "accepted" | "declined" | "blocked";
            instalmentAmount?: {
                /** Format: double */
                amount: number;
                /** @example EUR */
                currency: string;
            };
            instalmentCount?: number;
            affordabilityPolicyRef?: string;
            proposedByHuman?: boolean;
        };
        PaymentPlanResponse: {
            data: {
                id: string;
                accountId: string;
                /** @enum {string} */
                status: "proposed" | "accepted" | "declined" | "blocked";
                instalmentAmount?: {
                    /** Format: double */
                    amount: number;
                    /** @example EUR */
                    currency: string;
                };
                instalmentCount?: number;
                affordabilityPolicyRef?: string;
                proposedByHuman?: boolean;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    executeResolution: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    sessionId: string;
                    /** @enum {string} */
                    actionType: "request_meter_reread" | "request_meter_inspection" | "tariff_eligibility_check" | "refer_network_fault" | "reissue_bill" | "update_contact_preference" | "send_explanation_summary";
                    parameters?: {
                        [key: string]: string;
                    };
                };
            };
        };
        responses: {
            /** @description Resolution executed against the relevant system of record */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            sessionId: string;
                            actionType: string;
                            /** @enum {string} */
                            status: "executed" | "queued" | "blocked_by_policy" | "failed";
                            policyReference?: string;
                            /** @enum {string} */
                            targetSystem?: "billing" | "meter_data_management" | "collections" | "network_operator" | "crm";
                            blockReason?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Resolution falls outside approved policy or a vulnerability flag is open */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    proposePaymentPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    accountId: string;
                    instalmentAmount: {
                        /** Format: double */
                        amount: number;
                        /** @example EUR */
                        currency: string;
                    };
                    instalmentCount: number;
                    affordabilityPolicyRef?: string;
                    advisorReference: string;
                };
            };
        };
        responses: {
            /** @description Plan proposed within affordability policy by a human advisor */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            accountId: string;
                            /** @enum {string} */
                            status: "proposed" | "accepted" | "declined" | "blocked";
                            instalmentAmount?: {
                                /** Format: double */
                                amount: number;
                                /** @example EUR */
                                currency: string;
                            };
                            instalmentCount?: number;
                            affordabilityPolicyRef?: string;
                            proposedByHuman?: boolean;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Payment plans may not be proposed by an automated agent */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
