/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consumption
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { dataDefectRoutes } from "./data-defect.routes.js";
export { estimatedReadCorrectionRoutes } from "./estimated-read-correction.routes.js";
export { explanationRoutes } from "./explanation.routes.js";
