/**
 * Cohort DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cohorts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Cohort DTOs
 *
 * DDD: Application DTOs for Cohort use cases.
 */

import type { CreatePilotCohortRequestInput, ListPilotCohortsParams } from "@klarwatt/core/cohorts/types";

export type ListPilotCohortsInput = ListPilotCohortsParams;

export type CreatePilotCohortInput = CreatePilotCohortRequestInput;

export type ListPilotCohortsOutput = {};

export type CreatePilotCohortOutput = {};
