/**
 * Decision DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cohorts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Decision DTOs
 *
 * DDD: Application DTOs for Decision use cases.
 */

import type { DecideCohortOutcomeParams, DecideCohortOutcomeRequestInput } from "@klarwatt/core/cohorts/types";

export type DecideCohortOutcomeInput = DecideCohortOutcomeParams & DecideCohortOutcomeRequestInput;

export type DecideCohortOutcomeOutput = {};
