/**
 * Metric DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cohorts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Metric DTOs
 *
 * DDD: Application DTOs for Metric use cases.
 */

import type { GetCohortMetricsParams } from "@klarwatt/core/cohorts/types";

export type GetCohortMetricsInput = GetCohortMetricsParams;

export type GetCohortMetricsOutput = {};
