/**
 * GetCohortMetrics handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cohorts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getCohortMetrics } from "@klarwatt/api-server/domains/cohorts/handlers";
import type { CohortsDDDDependencies } from "@klarwatt/api-server/domains/cohorts";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@klarwatt/tests/shared";
import { COHORTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetCohortMetrics", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CohortsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CohortsDDDDependencies>(
      COHORTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetCohortMetrics, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { cohortId: entity.id };

    await getCohortMetrics(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetCohortMetrics.execute).toHaveBeenCalledWith(expect.objectContaining({ cohortId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { cohortId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetCohortMetrics, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getCohortMetrics(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
